### ISSUE TITLE
decor/schedule should be loadable during the build.

### ISSUE THREAD

**Issue by clmath** [ibm-js/decor#45]
This issue is the follow up of https://github.com/ibm-js/delite/issues/402

@asudoh said:
> Guessing @clmath is using node.js 0.8, where setImmediate() is not available. Create a PR adding process.nextTick() support to decor/schedule to cope with that. Also - setImmediate() runs after painting, etc. stuffs happens, whereas end-of-microtask queue like process.nextTick() and Mutation Observer callbacks runs before painting, etc. stuffs - Which means process.nextTick() is much closer to Object.observe() spec than setImmediate() is.

Actually I am using node v0.10.33. I have checked and `setImmediate()` is available. 
The problem is that the `has` plugin is set to not execute feature tests during the build since they could lead to incorrect modules inclusion in the layer. 
So `has("setImmediate")` is always false during the build even on node v0.10.33. 

So maybe a quick fix can be to have a `typeof window !== "undefined"` check before accessing window.

**Comment by asudoh** [comment]
Thanks @clmath for elaborating what the problem is.

> So `has("setImmediate”)` is always false during the build even on node v0.10.33.

This leads to a bigger problem than access to `window` object. If `has("setImmediate”)` as well as `has(“mutation-observer-api”)` are `false` the code tries to emit and receive [Web Messaging Event](http://www.w3.org/TR/2012/WD-webmessaging-20120313/), which is does not make sense for node.js (thus build) environment.

Given feature detection and branching upon its result is one of the key use cases for [has.js](https://github.com/phiggins42/has.js/), I’d suggest fixing the build system therefore.

**Comment by asudoh** [comment]
Updated my change introducing `process.nextTick()` support to check for `window` object existence, which may help non-browser, non-node.js environment.

**Comment by wkeese** [comment]
I don't think we should be bloating the code with support for non-browser non-Node (or old Node) environments.  No one will ever use that code branch.

IIUC we can work around this weirdness with the build system by simply changing:

```js
} else if (!has("setimmediate-api")) {
```

to

```js
} else if (!has("setimmediate-api") && typeof window !== "undefined") {
```

(like you did at https://github.com/asudoh/decor/commit/9d92fe4ecfa4220d140d412a3eb7a7a10e6a4809#diff-13ae235e4b68af8228369014f462fd2bR50)

**Comment by wkeese** [comment]
PS: About the build system, I agree it's confusing to not execute `has.add()` blocks at all, but OTOH builds are for browsers, so it would be silly to make a build based on feature-tests for what Node.js supports.

**Comment by asudoh** [comment]
I thought the build system loads code in two different ways? One is for inclusion in layers where no code runs and `has()` check should be based on running browser’s environment, another is for building plugins where `has()` check should be based on the build’s node.js environment?

**Comment by asudoh** [comment]
BTW basically I don’t think it would make sense to introduce a workaround specifically for our specific build system.

**Comment by wkeese** [comment]
IIUC, as you said, the build system needs to execute the code in plugins, specifically `writeLayer()`.   *But*, in order to execute the code in the `delite/handlebars!` plugin, it needs to load `delite/handlebar`'s direct and indirect dependencies, including `decor/schedule`.

> BTW basically I don’t think it would make sense to introduce a workaround specifically for our specific build system.

I don't know any other way to solve the problem.   FWIW, I did think of many other workarounds though.
The issue is this code block, which runs even if no one ever calls `schedule()`:

```js
if (has("mutation-observer-api")) {
	pseudoDiv.id = 0;
	new MutationObserver(runCallbacks).observe(pseudoDiv, {attributes: true});
} else if (!has("setimmediate-api")) {
	window.addEventListener("message", function (event) {
		if (event.data === uniqueId) {
			runCallbacks();
		}
	});
}
```

So some other workarounds are:


1. Change `if (!has("setimmediate-api")) to `if (has("host-browser") && !has("setimmediate-api"))`

2. The code above could be surrounded by `if (!has("builder")) { ... }`.   (That's the one `has()` flag that is set during builds.)

3. You could defer running the code above until the first call to `schedule()`.   Probably not a good idea, since it introduces a check on every call to `schedule()`.

**Comment by asudoh** [comment]
My point was that the environment running `writeLayer()` should have appropriate `has()` flags for node.js environment for build system (e.g. `true` for `has(“setimmediate-api”)`). @clmath have you tried mapping modules features.js depends on to an empty module, in case you didn’t want those to be included in the layer? (Otherwise I need to have better understanding on your concern)

In this context, if we set `has(“host-browser”)` for the node.js environment for build that’s better than nothing as we can go for 1., which is better aligned to overall structure of schedule.js, using `has()` for feature-based branching.

**Comment by cjolif** [comment]
Can't we be pragmatic? We have very little time for that right now. We have a one word workaround for schedule.js and we would have a day of work to adapt the build system. So what about for this release implementing the workaround and registering an issue on requirejs-dplugins/has so that later we can implement the proper solution?

**Comment by wkeese** [comment]
If it's only a day of work to fix the build system then I would go for that.

**Comment by cjolif** [comment]
@wkeese If you have it, feel free to do it, but we don't :(

**Comment by asudoh** [comment]
@wkeese @clmath Just to double-check, my interpretation of https://github.com/ibm-js/decor/issues/45#issuecomment-94593960 is `has(“host-browser”)` returns the right thing (`false`) is the build system, is it correct?

**Comment by wkeese** [comment]
@asudoh - that's my understanding too but I've never run the builder.

@cjolif - I have no interest in maintaining the builder code.  IMO we shouldn't have our own builder at all.  Especially if you don't have time to maintain it.

**Comment by asudoh** [comment]
+1 for not maintaining the builder by our own. I heard it’s for some of our plugins, but I think we should minimize what our builder code does at least. Probably [amodro-trace](https://github.com/amodrojs/amodro-trace) would help on that.

**Comment by clmath** [comment]
`has("host-browser")` will indeed be `false` during the build.

**Comment by asudoh** [comment]
Thanks @clmath for your feedback, let's go for 1. in https://github.com/ibm-js/decor/issues/45#issuecomment-94593960 for now then.

**Comment by clmath** [comment]
I created the issue against requirejs-dplugins/has.
