### ISSUE TITLE
add has("edge") flag for Edge

### ISSUE THREAD

**Issue by kgibb** [ibm-js/decor#57]
Windows 10. User agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240"

**Comment by wkeese** [comment]
Yes, of course, `has("ie")` returns undefined on all browsers except for IE.   This is expected behavior.  

Although Edge is forked from the IE code base it's technically a separate browser, with a new name.  So in the same way that `has("safari")` returns false on Chrome, `has("ie")` returns false on Edge.   Do you think it should be different?

We should though add a `has("edge")` flag.

**Comment by kgibb** [comment]
No the `has("edge")` flag should suffice.

**Comment by wkeese** [comment]
OK, I'll add has("edge") and make sure other flags (has("chrome"), has("safari"), has("webkit"), has("mozilla")) are false.
